using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Code2Obsidian.Analysis.Analyzers;

/// <summary>
/// Shared utility methods for analysis operations.
/// </summary>
internal static class AnalysisHelpers
{
    private static readonly string[] GeneratedFileSuffixes =
    {
        ".g.cs",
        ".g.i.cs",
        ".generated.cs",
        ".designer.cs",
        ".AssemblyInfo.cs",
        ".AssemblyAttributes.cs"
    };

    private static readonly string[] GeneratedHeaderMarkers =
    {
        "<auto-generated",
        "<autogenerated",
        "generated by the protocol buffer compiler",
        "this code was generated",
        "do not edit"
    };

    /// <summary>
    /// Custom display format that produces rich method signatures with access modifiers,
    /// return types, modifiers, and full parameter info including names, types, and defaults.
    /// Shared between TypeAnalyzer (constructor signatures) and MethodAnalyzer (method signatures).
    /// </summary>
    public static readonly SymbolDisplayFormat RichSignatureFormat = new(
        typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypes,
        memberOptions:
            SymbolDisplayMemberOptions.IncludeAccessibility |
            SymbolDisplayMemberOptions.IncludeModifiers |
            SymbolDisplayMemberOptions.IncludeType |
            SymbolDisplayMemberOptions.IncludeParameters |
            SymbolDisplayMemberOptions.IncludeRef,
        parameterOptions:
            SymbolDisplayParameterOptions.IncludeType |
            SymbolDisplayParameterOptions.IncludeName |
            SymbolDisplayParameterOptions.IncludeDefaultValue |
            SymbolDisplayParameterOptions.IncludeParamsRefOut,
        genericsOptions:
            SymbolDisplayGenericsOptions.IncludeTypeParameters |
            SymbolDisplayGenericsOptions.IncludeTypeConstraints,
        miscellaneousOptions:
            SymbolDisplayMiscellaneousOptions.UseSpecialTypes
    );

    /// <summary>
    /// Determines if a named type symbol belongs to one of the solution's project assemblies.
    /// Used to filter out external/framework types from note generation.
    /// </summary>
    public static bool IsUserType(INamedTypeSymbol? type, IReadOnlySet<string> projectAssemblyNames)
    {
        if (type is null) return false;
        if (type.ContainingAssembly is null) return false;
        if (!projectAssemblyNames.Contains(type.ContainingAssembly.Name)) return false;

        if (type.Locations.All(l => !l.IsInSource)) return false;

        var sourcePaths = type.Locations
            .Where(l => l.IsInSource)
            .Select(l => l.SourceTree?.FilePath)
            .Where(p => !string.IsNullOrWhiteSpace(p))
            .Cast<string>()
            .ToList();

        if (sourcePaths.Count > 0 && sourcePaths.All(IsGeneratedFilePath))
            return false;

        return true;
    }

    /// <summary>
    /// Maps a Roslyn Accessibility enum value to a lowercase C# access modifier string.
    /// </summary>
    public static string AccessibilityToString(Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.Private => "private",
            _ => ""
        };
    }

    /// <summary>
    /// Returns the source position of a symbol's first declaration for ordering members
    /// by their position in the source file. Returns int.MaxValue for symbols without
    /// syntax references (e.g., metadata-only symbols).
    /// </summary>
    public static int GetDeclarationOrder(ISymbol symbol)
    {
        return symbol.DeclaringSyntaxReferences.FirstOrDefault()?.Span.Start ?? int.MaxValue;
    }

    /// <summary>
    /// Extracts the summary text from a type's XML documentation comment.
    /// Returns null if no documentation or no summary element is present.
    /// </summary>
    public static string? GetTypeDocComment(INamedTypeSymbol type)
    {
        try
        {
            var xml = type.GetDocumentationCommentXml(expandIncludes: true, cancellationToken: default);
            if (string.IsNullOrWhiteSpace(xml)) return null;

            var root = System.Xml.Linq.XElement.Parse($"<root>{xml}</root>");
            var summary = root.Element("summary")?.Value?.Trim();
            if (string.IsNullOrWhiteSpace(summary)) return null;

            return NormalizeSpaces(summary);
        }
        catch
        {
            var fallback = type.GetDocumentationCommentXml(expandIncludes: false, cancellationToken: default);
            return string.IsNullOrWhiteSpace(fallback) ? null : fallback.Trim();
        }
    }

    /// <summary>
    /// Determines if a method symbol is "user code" (defined in source within the solution).
    /// Ported from Program.cs IsUserMethod() (lines 397-417), adapted to use
    /// assembly name strings instead of IAssemblySymbol equality.
    /// </summary>
    public static bool IsUserMethod(IMethodSymbol? method, IReadOnlySet<string> projectAssemblyNames)
    {
        if (method is null) return false;

        // Must come from one of our project assemblies (by name comparison)
        if (method.ContainingAssembly is null ||
            !projectAssemblyNames.Contains(method.ContainingAssembly.Name))
            return false;

        // Must have source (exclude metadata-only)
        if (method.Locations.All(l => !l.IsInSource)) return false;

        var sourcePaths = method.Locations
            .Where(l => l.IsInSource)
            .Select(l => l.SourceTree?.FilePath)
            .Where(p => !string.IsNullOrWhiteSpace(p))
            .Cast<string>()
            .ToList();

        if (sourcePaths.Count > 0 && sourcePaths.All(IsGeneratedFilePath))
            return false;

        // Skip generated/implicit bits
        if (method.IsImplicitlyDeclared) return false;

        // Skip property/event accessors and operators
        if (method.MethodKind is MethodKind.PropertyGet or MethodKind.PropertySet
            or MethodKind.EventAdd or MethodKind.EventRemove or MethodKind.EventRaise
            or MethodKind.BuiltinOperator or MethodKind.UserDefinedOperator)
            return false;

        return true;
    }

    /// <summary>
    /// Returns true if the source path is a known generated-code location/name pattern.
    /// </summary>
    public static bool IsGeneratedFilePath(string filePath)
    {
        if (string.IsNullOrWhiteSpace(filePath))
            return false;

        var normalized = filePath.Replace('\\', '/');

        if (normalized.Contains("/obj/", StringComparison.OrdinalIgnoreCase) ||
            normalized.Contains("/bin/", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        foreach (var suffix in GeneratedFileSuffixes)
        {
            if (normalized.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    /// <summary>
    /// Returns true if file-leading trivia indicates an auto-generated file header.
    /// </summary>
    public static bool HasGeneratedFileHeader(SyntaxNode root)
    {
        var leading = root.GetLeadingTrivia().ToFullString();
        if (string.IsNullOrWhiteSpace(leading))
            return false;

        foreach (var marker in GeneratedHeaderMarkers)
        {
            if (leading.Contains(marker, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    /// <summary>
    /// Extracts and formats XML doc comments for a method.
    /// Ported from Program.cs GetMethodDocstring() (lines 420-472).
    /// </summary>
    public static string? GetMethodDocstring(IMethodSymbol method)
    {
        try
        {
            var xml = method.GetDocumentationCommentXml(expandIncludes: true, cancellationToken: default);
            if (string.IsNullOrWhiteSpace(xml)) return null;

            // Wrap to ensure single root for parsing
            var root = System.Xml.Linq.XElement.Parse($"<root>{xml}</root>");

            var sb = new System.Text.StringBuilder();

            var summary = root.Element("summary")?.Value?.Trim();
            if (!string.IsNullOrWhiteSpace(summary))
                sb.AppendLine(NormalizeSpaces(summary));

            var parameters = root.Elements("param").ToList();
            if (parameters.Count > 0)
            {
                sb.AppendLine();
                sb.AppendLine("Parameters:");
                foreach (var p in parameters)
                {
                    var name = p.Attribute("name")?.Value ?? "";
                    var text = NormalizeSpaces(p.Value?.Trim() ?? "");
                    sb.AppendLine($"- {name}: {text}");
                }
            }

            var returns = root.Element("returns")?.Value?.Trim();
            if (!string.IsNullOrWhiteSpace(returns))
            {
                sb.AppendLine();
                sb.AppendLine($"Returns: {NormalizeSpaces(returns)}");
            }

            var remarks = root.Element("remarks")?.Value?.Trim();
            if (!string.IsNullOrWhiteSpace(remarks))
            {
                sb.AppendLine();
                sb.AppendLine(NormalizeSpaces(remarks));
            }

            var result = sb.ToString().Trim();
            return string.IsNullOrWhiteSpace(result) ? xml.Trim() : result;
        }
        catch
        {
            // If the XML isn't well-formed, just return the raw text
            var fallback = method.GetDocumentationCommentXml(expandIncludes: false, cancellationToken: default);
            return string.IsNullOrWhiteSpace(fallback) ? null : fallback.Trim();
        }
    }

    /// <summary>
    /// Normalizes whitespace in a string (collapses runs of whitespace to single space).
    /// Ported from Program.cs NormalizeSpaces() (lines 474-492).
    /// </summary>
    public static string NormalizeSpaces(string s)
    {
        if (string.IsNullOrEmpty(s)) return s;
        var b = new System.Text.StringBuilder(s.Length);
        bool ws = false;
        foreach (var ch in s)
        {
            if (char.IsWhiteSpace(ch))
            {
                if (!ws) { b.Append(' '); ws = true; }
            }
            else
            {
                b.Append(ch);
                ws = false;
            }
        }
        return b.ToString().Trim();
    }

    /// <summary>
    /// Computes cyclomatic complexity for a method declaration via syntax-tree walking.
    /// Base value is 1. Each branch construct adds 1. Nested lambdas and local functions
    /// are excluded from the containing method's complexity count.
    /// </summary>
    public static int ComputeCyclomaticComplexity(BaseMethodDeclarationSyntax declaration)
    {
        // Determine the syntax node to walk: Body (block), ExpressionBody, or neither
        SyntaxNode? walkTarget = declaration.Body;
        if (walkTarget is null && declaration is MethodDeclarationSyntax methodDecl)
        {
            walkTarget = methodDecl.ExpressionBody;
        }

        // Abstract/extern methods with no body or expression body
        if (walkTarget is null)
            return 1;

        int complexity = 1;

        foreach (var node in walkTarget.DescendantNodes(ShouldDescend))
        {
            switch (node)
            {
                case IfStatementSyntax:
                case WhileStatementSyntax:
                case ForStatementSyntax:
                case ForEachStatementSyntax:
                case DoStatementSyntax:
                case CaseSwitchLabelSyntax:
                case CasePatternSwitchLabelSyntax:
                case CatchClauseSyntax:
                case ConditionalExpressionSyntax:
                case ConditionalAccessExpressionSyntax:
                    complexity++;
                    break;

                case BinaryExpressionSyntax binary when
                    binary.IsKind(SyntaxKind.LogicalAndExpression) ||
                    binary.IsKind(SyntaxKind.LogicalOrExpression) ||
                    binary.IsKind(SyntaxKind.CoalesceExpression):
                    complexity++;
                    break;

                case SwitchExpressionArmSyntax arm when arm.Pattern is not DiscardPatternSyntax:
                    complexity++;
                    break;
            }
        }

        return complexity;
    }

    /// <summary>
    /// Determines whether to descend into a syntax node during complexity traversal.
    /// Prunes nested lambdas, anonymous methods, and local functions -- these have
    /// their own complexity and should not inflate the containing method's count.
    /// </summary>
    private static bool ShouldDescend(SyntaxNode node) =>
        node is not (SimpleLambdaExpressionSyntax
            or ParenthesizedLambdaExpressionSyntax
            or LocalFunctionStatementSyntax
            or AnonymousMethodExpressionSyntax);
}
