using System.Diagnostics;
using System.Net.WebSockets;
using System.Runtime.InteropServices;

namespace Code2Obsidian.Enrichment.Config;

/// <summary>
/// Manages a local pool of Codex app-server processes listening on websocket endpoints.
/// </summary>
public sealed class CodexAppServerPool : IAsyncDisposable, IDisposable
{
    private static readonly TimeSpan StartupTimeout = TimeSpan.FromSeconds(20);
    private static readonly TimeSpan StartupProbeInterval = TimeSpan.FromMilliseconds(250);
    private static readonly TimeSpan ConnectAttemptTimeout = TimeSpan.FromSeconds(1);
    private static readonly TimeSpan RestartRetryDelay = TimeSpan.FromSeconds(1);
    private static readonly TimeSpan ForcedRestartThrottle = TimeSpan.FromSeconds(2);

    private readonly Dictionary<string, Process> _processesByEndpoint = new(StringComparer.OrdinalIgnoreCase);
    private readonly Dictionary<string, DateTimeOffset> _lastForcedRestartByEndpoint = new(StringComparer.OrdinalIgnoreCase);
    private readonly object _gate = new();
    private readonly CancellationTokenSource _lifetimeCts = new();
    private readonly string? _wslDistro;
    private readonly string? _workingDirectory;
    private readonly SerenaMcpConfig? _serena;
    private bool _disposed;

    private CodexAppServerPool(
        IReadOnlyList<string> endpoints,
        string? wslDistro,
        string? workingDirectory,
        SerenaMcpConfig? serena)
    {
        Endpoints = endpoints;
        _wslDistro = wslDistro;
        _workingDirectory = workingDirectory;
        _serena = serena;
    }

    public IReadOnlyList<string> Endpoints { get; }

    /// <summary>
    /// Starts a Codex app-server process for each endpoint in the generated pool.
    /// Endpoints are generated by incrementing the base endpoint port.
    /// </summary>
    public static async Task<CodexAppServerPool> StartAsync(
        int poolSize,
        string baseEndpoint,
        string? wslDistro,
        CancellationToken ct,
        string? workingDirectory = null,
        SerenaMcpConfig? serena = null)
    {
        if (poolSize < 1)
            throw new ArgumentOutOfRangeException(nameof(poolSize), "Pool size must be >= 1.");

        var endpoints = BuildEndpoints(baseEndpoint, poolSize);
        var pool = new CodexAppServerPool(endpoints, wslDistro, workingDirectory, serena);

        try
        {
            foreach (var endpoint in endpoints)
            {
                pool.StartAndTrackServer(endpoint, serena);
            }

            await WaitForAllEndpointsAsync(endpoints, ct);
            return pool;
        }
        catch
        {
            pool.Dispose();
            throw;
        }
    }

    /// <summary>
    /// Returns the endpoint list that would be used for a pool from the given base endpoint.
    /// </summary>
    public static IReadOnlyList<string> PreviewEndpoints(string baseEndpoint, int poolSize) =>
        BuildEndpoints(baseEndpoint, poolSize);

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        _lifetimeCts.Cancel();

        List<Process> processes;
        lock (_gate)
        {
            processes = _processesByEndpoint.Values
                .Distinct()
                .ToList();
            _processesByEndpoint.Clear();
        }

        foreach (var process in processes)
        {
            TryKill(process);
            process.Dispose();
        }

        _lifetimeCts.Dispose();
    }

    public ValueTask DisposeAsync()
    {
        Dispose();
        return ValueTask.CompletedTask;
    }

    /// <summary>
    /// Requests a forced restart of a managed endpoint process.
    /// Returns false when the endpoint is not currently tracked by this pool.
    /// </summary>
    public bool RequestRestart(string endpoint, string reason)
    {
        if (string.IsNullOrWhiteSpace(endpoint))
            return false;

        Process? process;
        string? matchedEndpoint;
        var normalized = NormalizeEndpoint(endpoint);
        var alternate = endpoint.Trim();
        var now = DateTimeOffset.UtcNow;

        lock (_gate)
        {
            if (_disposed)
                return false;

            if (_processesByEndpoint.TryGetValue(normalized, out process))
            {
                matchedEndpoint = normalized;
            }
            else if (_processesByEndpoint.TryGetValue(alternate, out process))
            {
                matchedEndpoint = alternate;
            }
            else
            {
                return false;
            }

            if (_lastForcedRestartByEndpoint.TryGetValue(matchedEndpoint, out var last) &&
                now - last < ForcedRestartThrottle)
            {
                return false;
            }

            _lastForcedRestartByEndpoint[matchedEndpoint] = now;
        }

        CodexLogBoard.Report(matchedEndpoint, $"restart requested ({reason})");
        TryKill(process);
        return true;
    }

    /// <summary>
    /// Requests a forced restart and waits for the replacement endpoint to become reachable.
    /// Returns false only when the endpoint is not tracked by this pool.
    /// </summary>
    public async Task<bool> RequestRestartAndWaitAsync(string endpoint, string reason, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(endpoint))
            return false;

        var normalized = NormalizeEndpoint(endpoint);
        bool tracked;
        lock (_gate)
        {
            tracked = _processesByEndpoint.ContainsKey(normalized) ||
                      _processesByEndpoint.ContainsKey(endpoint.Trim());
        }

        if (!tracked)
            return false;

        _ = RequestRestart(endpoint, reason);
        await WaitForEndpointAsync(normalized, ct);
        return true;
    }

    private void StartAndTrackServer(string endpoint, SerenaMcpConfig? serena)
    {
        var process = StartServer(endpoint, _wslDistro, OnProcessExited, _workingDirectory, serena);
        lock (_gate)
        {
            _processesByEndpoint[endpoint] = process;
        }
    }

    private static Process StartServer(
        string endpoint,
        string? wslDistro,
        Action<string, Process>? onExited = null,
        string? workingDirectory = null,
        SerenaMcpConfig? serena = null)
    {
        var psi = BuildServerStartInfo(endpoint, wslDistro, serena);
        if (!string.IsNullOrWhiteSpace(workingDirectory))
            psi.WorkingDirectory = workingDirectory;

        var process = new Process
        {
            StartInfo = psi,
            EnableRaisingEvents = true
        };

        process.ErrorDataReceived += (_, args) =>
        {
            if (!string.IsNullOrWhiteSpace(args.Data))
                CodexLogBoard.Report(endpoint, args.Data);
        };
        process.OutputDataReceived += (_, args) =>
        {
            if (!string.IsNullOrWhiteSpace(args.Data))
                CodexLogBoard.Report(endpoint, args.Data);
        };
        process.Exited += (_, _) =>
        {
            try
            {
                CodexLogBoard.Report(endpoint, $"process exited ({process.ExitCode})");
                onExited?.Invoke(endpoint, process);
            }
            catch
            {
                // best-effort
            }
        };

        if (!process.Start())
            throw new InvalidOperationException($"Failed to start codex app-server for endpoint '{endpoint}'.");

        CodexLogBoard.Report(endpoint, "starting codex app-server...");
        process.BeginOutputReadLine();
        process.BeginErrorReadLine();
        return process;
    }

    private void OnProcessExited(string endpoint, Process exitedProcess)
    {
        _ = Task.Run(() => RestartEndpointLoopAsync(endpoint, exitedProcess));
    }

    private async Task RestartEndpointLoopAsync(string endpoint, Process exitedProcess)
    {
        try
        {
            for (var attempt = 1; ; attempt++)
            {
                if (!ShouldRestart(endpoint, exitedProcess))
                {
                    SafeDisposeProcess(exitedProcess);
                    return;
                }

                if (_disposed)
                {
                    SafeDisposeProcess(exitedProcess);
                    return;
                }

                Process? replacement = null;

                try
                {
                    CodexLogBoard.Report(endpoint, $"restarting codex app-server (attempt {attempt})...");
                    replacement = StartServer(endpoint, _wslDistro, OnProcessExited, _workingDirectory, _serena);

                    lock (_gate)
                    {
                        if (_disposed)
                        {
                            TryKill(replacement);
                            SafeDisposeProcess(replacement);
                            SafeDisposeProcess(exitedProcess);
                            return;
                        }

                        _processesByEndpoint[endpoint] = replacement;
                    }

                    await WaitForEndpointAsync(endpoint, _lifetimeCts.Token);
                    SafeDisposeProcess(exitedProcess);
                    CodexLogBoard.Report(endpoint, $"codex app-server restart complete (attempt {attempt})");
                    return;
                }
                catch (OperationCanceledException) when (_disposed || _lifetimeCts.IsCancellationRequested)
                {
                    if (replacement is not null)
                        DemoteFailedReplacement(endpoint, replacement, exitedProcess);
                    SafeDisposeProcess(exitedProcess);
                    return;
                }
                catch (Exception ex)
                {
                    if (replacement is not null)
                        DemoteFailedReplacement(endpoint, replacement, exitedProcess);

                    CodexLogBoard.Report(endpoint, $"restart attempt {attempt} failed: {ex.Message}");
                    try
                    {
                        await Task.Delay(RestartRetryDelay, _lifetimeCts.Token);
                    }
                    catch (OperationCanceledException)
                    {
                        SafeDisposeProcess(exitedProcess);
                        return;
                    }
                }
            }
        }
        catch
        {
            // best-effort auto-restart loop
        }
    }

    private void DemoteFailedReplacement(string endpoint, Process replacement, Process exitedProcess)
    {
        lock (_gate)
        {
            if (_processesByEndpoint.TryGetValue(endpoint, out var tracked) &&
                ReferenceEquals(tracked, replacement))
            {
                _processesByEndpoint[endpoint] = exitedProcess;
            }
        }

        TryKill(replacement);
        SafeDisposeProcess(replacement);
    }

    private bool ShouldRestart(string endpoint, Process exitedProcess)
    {
        if (_disposed)
            return false;

        lock (_gate)
        {
            if (_disposed)
                return false;

            return _processesByEndpoint.TryGetValue(endpoint, out var tracked) &&
                   ReferenceEquals(tracked, exitedProcess);
        }
    }

    private static void SafeDisposeProcess(Process process)
    {
        try
        {
            process.Dispose();
        }
        catch
        {
            // best-effort cleanup
        }
    }

    private static ProcessStartInfo BuildServerStartInfo(string endpoint, string? wslDistro, SerenaMcpConfig? serena)
    {
        var serenaOverrides = SerenaMcpSettings.BuildCodexConfigOverrides(serena);
        var psi = new ProcessStartInfo
        {
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true
        };

        // If the main app runs on Windows, force pool processes into WSL.
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            var distro = string.IsNullOrWhiteSpace(wslDistro)
                ? Environment.GetEnvironmentVariable("CODEX_POOL_WSL_DISTRO")
                : wslDistro;
            if (string.IsNullOrWhiteSpace(distro))
                distro = "Ubuntu";
            psi.FileName = "wsl.exe";
            if (!string.IsNullOrWhiteSpace(distro))
            {
                psi.ArgumentList.Add("--distribution");
                psi.ArgumentList.Add(distro);
            }

            // Use a login shell so user PATH setup (e.g. nvm-managed codex) is available.
            psi.ArgumentList.Add("bash");
            psi.ArgumentList.Add("-lc");
            psi.ArgumentList.Add(BuildWslLaunchCommand(endpoint, serenaOverrides));
            return psi;
        }

        psi.FileName = "codex";
        psi.ArgumentList.Add("app-server");
        foreach (var configOverride in serenaOverrides)
        {
            psi.ArgumentList.Add("-c");
            psi.ArgumentList.Add(configOverride);
        }
        psi.ArgumentList.Add("--listen");
        psi.ArgumentList.Add(endpoint);
        return psi;
    }

    private static string BuildWslLaunchCommand(string endpoint, IReadOnlyList<string> serenaOverrides)
    {
        var codexBin = Environment.GetEnvironmentVariable("CODEX_POOL_WSL_CODEX_BIN");
        var codexTarget = string.IsNullOrWhiteSpace(codexBin) ? "codex" : codexBin;
        var quotedCodex = BashSingleQuote(codexTarget);
        var quotedEndpoint = BashSingleQuote(endpoint);
        var configArgs = string.Join(" ",
            serenaOverrides.Select(value => $"-c {BashSingleQuote(value)}"));

        return $$"""
            set -e

            if [ -s "$HOME/.nvm/nvm.sh" ]; then
              . "$HOME/.nvm/nvm.sh" >/dev/null 2>&1 || true
            fi

            if ! command -v {{quotedCodex}} >/dev/null 2>&1; then
              echo "WSL codex not found on PATH. Install Codex in WSL or set CODEX_POOL_WSL_CODEX_BIN." >&2
              exit 127
            fi

            exec {{quotedCodex}} app-server {{configArgs}} --listen {{quotedEndpoint}}
            """;
    }

    private static string BashSingleQuote(string value)
    {
        return "'" + value.Replace("'", "'\"'\"'") + "'";
    }

    private static string NormalizeEndpoint(string endpoint)
    {
        return endpoint.Trim().TrimEnd('/');
    }

    private static IReadOnlyList<string> BuildEndpoints(string baseEndpoint, int poolSize)
    {
        if (!Uri.TryCreate(baseEndpoint, UriKind.Absolute, out var baseUri))
            throw new InvalidOperationException($"Invalid Codex base endpoint: '{baseEndpoint}'.");

        if (!baseUri.Scheme.Equals("ws", StringComparison.OrdinalIgnoreCase) &&
            !baseUri.Scheme.Equals("wss", StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidOperationException(
                $"Codex pool base endpoint must use ws:// or wss://, got '{baseEndpoint}'.");
        }

        var startPort = baseUri.Port;
        var maxPort = startPort + poolSize - 1;
        if (maxPort > 65535)
        {
            throw new InvalidOperationException(
                $"Pool size {poolSize} from base port {startPort} exceeds max TCP port 65535.");
        }

        var endpoints = new List<string>(poolSize);
        for (var i = 0; i < poolSize; i++)
        {
            var builder = new UriBuilder(baseUri)
            {
                Port = startPort + i
            };
            endpoints.Add(builder.Uri.ToString().TrimEnd('/'));
        }

        return endpoints;
    }

    private static async Task WaitForAllEndpointsAsync(IReadOnlyList<string> endpoints, CancellationToken ct)
    {
        var tasks = endpoints.Select(endpoint => WaitForEndpointAsync(endpoint, ct));
        await Task.WhenAll(tasks);
    }

    private static async Task WaitForEndpointAsync(string endpoint, CancellationToken ct)
    {
        var uri = new Uri(endpoint);
        var deadline = DateTime.UtcNow + StartupTimeout;
        Exception? lastException = null;

        while (DateTime.UtcNow < deadline)
        {
            ct.ThrowIfCancellationRequested();
            try
            {
                using var ws = new ClientWebSocket();
                using var attemptCts = CancellationTokenSource.CreateLinkedTokenSource(ct);
                attemptCts.CancelAfter(ConnectAttemptTimeout);
                await ws.ConnectAsync(uri, attemptCts.Token);
                // Successful websocket handshake means endpoint is ready.
                // Do not require graceful close handshake here; some servers drop probe sockets.
                return;
            }
            catch (Exception ex) when (IsTransientStartupException(ex, ct))
            {
                lastException = ex;
                await Task.Delay(StartupProbeInterval, ct);
            }
        }

        throw new TimeoutException(
            $"Timed out waiting for codex app-server endpoint '{endpoint}' to become ready. " +
            $"Last error: {lastException?.Message ?? "unknown"}");
    }

    private static bool IsTransientStartupException(Exception ex, CancellationToken outerToken)
    {
        if (ex is OperationCanceledException && outerToken.IsCancellationRequested)
            return false;

        return ex is OperationCanceledException
            or WebSocketException
            or HttpRequestException
            or InvalidOperationException;
    }

    private static void TryKill(Process process)
    {
        try
        {
            if (process.HasExited)
                return;

            process.Kill(entireProcessTree: true);
            process.WaitForExit(2000);
        }
        catch
        {
            // Best effort cleanup.
        }
    }
}
