using System.Diagnostics;
using System.Net.WebSockets;
using System.Runtime.InteropServices;

namespace Code2Obsidian.Enrichment.Config;

/// <summary>
/// Manages a local pool of Codex app-server processes listening on websocket endpoints.
/// </summary>
public sealed class CodexAppServerPool : IAsyncDisposable, IDisposable
{
    private static readonly TimeSpan StartupTimeout = TimeSpan.FromSeconds(20);
    private static readonly TimeSpan StartupProbeInterval = TimeSpan.FromMilliseconds(250);
    private static readonly TimeSpan ConnectAttemptTimeout = TimeSpan.FromSeconds(1);

    private readonly List<Process> _processes;
    private bool _disposed;

    private CodexAppServerPool(IReadOnlyList<string> endpoints, List<Process> processes)
    {
        Endpoints = endpoints;
        _processes = processes;
    }

    public IReadOnlyList<string> Endpoints { get; }

    /// <summary>
    /// Starts a Codex app-server process for each endpoint in the generated pool.
    /// Endpoints are generated by incrementing the base endpoint port.
    /// </summary>
    public static async Task<CodexAppServerPool> StartAsync(
        int poolSize,
        string baseEndpoint,
        string? wslDistro,
        CancellationToken ct)
    {
        if (poolSize < 1)
            throw new ArgumentOutOfRangeException(nameof(poolSize), "Pool size must be >= 1.");

        var endpoints = BuildEndpoints(baseEndpoint, poolSize);
        var processes = new List<Process>(poolSize);

        try
        {
            foreach (var endpoint in endpoints)
            {
                var process = StartServer(endpoint, wslDistro);
                processes.Add(process);
            }

            await WaitForAllEndpointsAsync(endpoints, ct);
            return new CodexAppServerPool(endpoints, processes);
        }
        catch
        {
            foreach (var process in processes)
            {
                TryKill(process);
                process.Dispose();
            }
            throw;
        }
    }

    /// <summary>
    /// Returns the endpoint list that would be used for a pool from the given base endpoint.
    /// </summary>
    public static IReadOnlyList<string> PreviewEndpoints(string baseEndpoint, int poolSize) =>
        BuildEndpoints(baseEndpoint, poolSize);

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;

        foreach (var process in _processes)
        {
            TryKill(process);
            process.Dispose();
        }
    }

    public ValueTask DisposeAsync()
    {
        Dispose();
        return ValueTask.CompletedTask;
    }

    private static Process StartServer(string endpoint, string? wslDistro)
    {
        var psi = BuildServerStartInfo(endpoint, wslDistro);

        var process = new Process
        {
            StartInfo = psi,
            EnableRaisingEvents = true
        };

        process.ErrorDataReceived += (_, args) =>
        {
            if (!string.IsNullOrWhiteSpace(args.Data))
                CodexLogBoard.Report(endpoint, args.Data);
        };
        process.OutputDataReceived += (_, args) =>
        {
            if (!string.IsNullOrWhiteSpace(args.Data))
                CodexLogBoard.Report(endpoint, args.Data);
        };
        process.Exited += (_, _) =>
        {
            try
            {
                CodexLogBoard.Report(endpoint, $"process exited ({process.ExitCode})");
            }
            catch
            {
                // best-effort
            }
        };

        if (!process.Start())
            throw new InvalidOperationException($"Failed to start codex app-server for endpoint '{endpoint}'.");

        CodexLogBoard.Report(endpoint, "starting codex app-server...");
        process.BeginOutputReadLine();
        process.BeginErrorReadLine();
        return process;
    }

    private static ProcessStartInfo BuildServerStartInfo(string endpoint, string? wslDistro)
    {
        var psi = new ProcessStartInfo
        {
            UseShellExecute = false,
            RedirectStandardOutput = true,
            RedirectStandardError = true
        };

        // If the main app runs on Windows, force pool processes into WSL.
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            var distro = string.IsNullOrWhiteSpace(wslDistro)
                ? Environment.GetEnvironmentVariable("CODEX_POOL_WSL_DISTRO")
                : wslDistro;
            if (string.IsNullOrWhiteSpace(distro))
                distro = "Ubuntu";
            psi.FileName = "wsl.exe";
            if (!string.IsNullOrWhiteSpace(distro))
            {
                psi.ArgumentList.Add("--distribution");
                psi.ArgumentList.Add(distro);
            }

            // Use a login shell so user PATH setup (e.g. nvm-managed codex) is available.
            psi.ArgumentList.Add("bash");
            psi.ArgumentList.Add("-lc");
            psi.ArgumentList.Add(BuildWslLaunchCommand(endpoint));
            return psi;
        }

        psi.FileName = "codex";
        psi.ArgumentList.Add("app-server");
        psi.ArgumentList.Add("--listen");
        psi.ArgumentList.Add(endpoint);
        return psi;
    }

    private static string BuildWslLaunchCommand(string endpoint)
    {
        var codexBin = Environment.GetEnvironmentVariable("CODEX_POOL_WSL_CODEX_BIN");
        var codexTarget = string.IsNullOrWhiteSpace(codexBin) ? "codex" : codexBin;
        var quotedCodex = BashSingleQuote(codexTarget);
        var quotedEndpoint = BashSingleQuote(endpoint);

        return $$"""
            set -e

            if [ -s "$HOME/.nvm/nvm.sh" ]; then
              . "$HOME/.nvm/nvm.sh" >/dev/null 2>&1 || true
            fi

            if ! command -v {{quotedCodex}} >/dev/null 2>&1; then
              echo "WSL codex not found on PATH. Install Codex in WSL or set CODEX_POOL_WSL_CODEX_BIN." >&2
              exit 127
            fi

            exec {{quotedCodex}} app-server --listen {{quotedEndpoint}}
            """;
    }

    private static string BashSingleQuote(string value)
    {
        return "'" + value.Replace("'", "'\"'\"'") + "'";
    }

    private static IReadOnlyList<string> BuildEndpoints(string baseEndpoint, int poolSize)
    {
        if (!Uri.TryCreate(baseEndpoint, UriKind.Absolute, out var baseUri))
            throw new InvalidOperationException($"Invalid Codex base endpoint: '{baseEndpoint}'.");

        if (!baseUri.Scheme.Equals("ws", StringComparison.OrdinalIgnoreCase) &&
            !baseUri.Scheme.Equals("wss", StringComparison.OrdinalIgnoreCase))
        {
            throw new InvalidOperationException(
                $"Codex pool base endpoint must use ws:// or wss://, got '{baseEndpoint}'.");
        }

        var startPort = baseUri.Port;
        var maxPort = startPort + poolSize - 1;
        if (maxPort > 65535)
        {
            throw new InvalidOperationException(
                $"Pool size {poolSize} from base port {startPort} exceeds max TCP port 65535.");
        }

        var endpoints = new List<string>(poolSize);
        for (var i = 0; i < poolSize; i++)
        {
            var builder = new UriBuilder(baseUri)
            {
                Port = startPort + i
            };
            endpoints.Add(builder.Uri.ToString().TrimEnd('/'));
        }

        return endpoints;
    }

    private static async Task WaitForAllEndpointsAsync(IReadOnlyList<string> endpoints, CancellationToken ct)
    {
        var tasks = endpoints.Select(endpoint => WaitForEndpointAsync(endpoint, ct));
        await Task.WhenAll(tasks);
    }

    private static async Task WaitForEndpointAsync(string endpoint, CancellationToken ct)
    {
        var uri = new Uri(endpoint);
        var deadline = DateTime.UtcNow + StartupTimeout;
        Exception? lastException = null;

        while (DateTime.UtcNow < deadline)
        {
            ct.ThrowIfCancellationRequested();
            try
            {
                using var ws = new ClientWebSocket();
                using var attemptCts = CancellationTokenSource.CreateLinkedTokenSource(ct);
                attemptCts.CancelAfter(ConnectAttemptTimeout);
                await ws.ConnectAsync(uri, attemptCts.Token);
                // Successful websocket handshake means endpoint is ready.
                // Do not require graceful close handshake here; some servers drop probe sockets.
                return;
            }
            catch (Exception ex) when (IsTransientStartupException(ex, ct))
            {
                lastException = ex;
                await Task.Delay(StartupProbeInterval, ct);
            }
        }

        throw new TimeoutException(
            $"Timed out waiting for codex app-server endpoint '{endpoint}' to become ready. " +
            $"Last error: {lastException?.Message ?? "unknown"}");
    }

    private static bool IsTransientStartupException(Exception ex, CancellationToken outerToken)
    {
        if (ex is OperationCanceledException && outerToken.IsCancellationRequested)
            return false;

        return ex is OperationCanceledException
            or WebSocketException
            or HttpRequestException
            or InvalidOperationException;
    }

    private static void TryKill(Process process)
    {
        try
        {
            if (process.HasExited)
                return;

            process.Kill(entireProcessTree: true);
            process.WaitForExit(2000);
        }
        catch
        {
            // Best effort cleanup.
        }
    }
}
